/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "reverse.h"

int *
reverse_1_svc(A *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	 
	int temp = argp->a;
	int rev_num = 0;
	
	while(temp)
	{
		int rem = temp % 10;
		rev_num = rev_num * 10 + rem;
		temp = temp/10;
	}
	
	result = rev_num;
	

	return &result;
}
