/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "reverse.h"


void
prog_rev_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	A  reverse_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PROG_REV, VER_REV, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	printf("Enter Number: \n");
	scanf("%d", &reverse_1_arg.a);
	
	result_1 = reverse_1(&reverse_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	printf("Result: %d \n", *result_1);
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	prog_rev_1 (host);
exit (0);
}
