/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _REVERSE_H_RPCGEN
#define _REVERSE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct A {
	int a;
};
typedef struct A A;

#define PROG_REV 0x1234567
#define VER_REV 1

#if defined(__STDC__) || defined(__cplusplus)
#define reverse 1
extern  int * reverse_1(A *, CLIENT *);
extern  int * reverse_1_svc(A *, struct svc_req *);
extern int prog_rev_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define reverse 1
extern  int * reverse_1();
extern  int * reverse_1_svc();
extern int prog_rev_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_A (XDR *, A*);

#else /* K&R C */
extern bool_t xdr_A ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_REVERSE_H_RPCGEN */
