/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "assign6.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
palindrome_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		strings palindrome_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case palindrome:
		_xdr_argument = (xdrproc_t) xdr_strings;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) palindrome_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
leap_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		numb leap_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case leap:
		_xdr_argument = (xdrproc_t) xdr_numb;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) leap_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
gcd_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		numb gcd_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case gcd:
		_xdr_argument = (xdrproc_t) xdr_numb;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) gcd_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
root_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		numb root_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case root:
		_xdr_argument = (xdrproc_t) xdr_numb;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) root_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
swap_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		numb swap_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case swap:
		_xdr_argument = (xdrproc_t) xdr_numb;
		_xdr_result = (xdrproc_t) xdr_numb;
		local = (char *(*)(char *, struct svc_req *)) swap_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
state_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		arr state_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case state:
		_xdr_argument = (xdrproc_t) xdr_arr;
		_xdr_result = (xdrproc_t) xdr_stat;
		local = (char *(*)(char *, struct svc_req *)) state_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
cmp_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		strings cmp_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case cmp:
		_xdr_argument = (xdrproc_t) xdr_strings;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) cmp_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
sub_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		strings sub_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case sub:
		_xdr_argument = (xdrproc_t) xdr_strings;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) sub_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
cont_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		strings cont_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case cont:
		_xdr_argument = (xdrproc_t) xdr_strings;
		_xdr_result = (xdrproc_t) xdr_strings;
		local = (char *(*)(char *, struct svc_req *)) cont_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
rev_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		arr rev_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case rev:
		_xdr_argument = (xdrproc_t) xdr_arr;
		_xdr_result = (xdrproc_t) xdr_arr;
		local = (char *(*)(char *, struct svc_req *)) rev_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (PALINDROME_PROG, PALINDROME_VERS);
	pmap_unset (LEAP_PROG, LEAP_VERS);
	pmap_unset (GCD_PROG, GCD_VERS);
	pmap_unset (ROOT_PROG, ROOT_VERS);
	pmap_unset (SWAP_PROG, SWAP_VERS);
	pmap_unset (STATE_PROG, STATE_VERS);
	pmap_unset (CMP_PROG, CMP_VERS);
	pmap_unset (SUB_PROG, SUB_VERS);
	pmap_unset (CONT_PROG, CONT_VERS);
	pmap_unset (REV_PROG, REV_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, PALINDROME_PROG, PALINDROME_VERS, palindrome_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (PALINDROME_PROG, PALINDROME_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, LEAP_PROG, LEAP_VERS, leap_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (LEAP_PROG, LEAP_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, GCD_PROG, GCD_VERS, gcd_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (GCD_PROG, GCD_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, ROOT_PROG, ROOT_VERS, root_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (ROOT_PROG, ROOT_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, SWAP_PROG, SWAP_VERS, swap_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (SWAP_PROG, SWAP_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, STATE_PROG, STATE_VERS, state_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (STATE_PROG, STATE_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, CMP_PROG, CMP_VERS, cmp_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CMP_PROG, CMP_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, SUB_PROG, SUB_VERS, sub_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (SUB_PROG, SUB_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, CONT_PROG, CONT_VERS, cont_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CONT_PROG, CONT_VERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, REV_PROG, REV_VERS, rev_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (REV_PROG, REV_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, PALINDROME_PROG, PALINDROME_VERS, palindrome_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (PALINDROME_PROG, PALINDROME_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, LEAP_PROG, LEAP_VERS, leap_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (LEAP_PROG, LEAP_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, GCD_PROG, GCD_VERS, gcd_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (GCD_PROG, GCD_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, ROOT_PROG, ROOT_VERS, root_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (ROOT_PROG, ROOT_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, SWAP_PROG, SWAP_VERS, swap_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (SWAP_PROG, SWAP_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, STATE_PROG, STATE_VERS, state_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (STATE_PROG, STATE_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, CMP_PROG, CMP_VERS, cmp_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CMP_PROG, CMP_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, SUB_PROG, SUB_VERS, sub_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (SUB_PROG, SUB_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, CONT_PROG, CONT_VERS, cont_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CONT_PROG, CONT_VERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, REV_PROG, REV_VERS, rev_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (REV_PROG, REV_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
