/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "assign6.h"


void
palindrome_prog_1(char *host, char msg[])
{
	CLIENT *clnt;
	int  *result_1;
	strings  palindrome_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PALINDROME_PROG, PALINDROME_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	int l=strlen(msg);
	int i=0;
	for(i=0;i<=l;i++)
	{
		palindrome_1_arg.str1[i]=msg[i];
	}
	//printf("\n in client %s",msg);
	result_1 = palindrome_1(&palindrome_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		if(*result_1 == 0)
		{
			printf("\nString is palindrome");
		}
		else
		{
			printf("\nString is Not palindrome");
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
leap_prog_1(char *host,int year)
{
	CLIENT *clnt;
	int  *result_1;
	numb  leap_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, LEAP_PROG, LEAP_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	leap_1_arg.a=year;
	result_1 = leap_1(&leap_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else
	{
		if(*result_1 == 0)
		{
			printf("\n Not a leap year");
		}else
		{
			printf("\n yes it is a leap year");
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
gcd_prog_1(char *host,int n1, int n2)
{
	CLIENT *clnt;
	int  *result_1;
	numb  gcd_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, GCD_PROG, GCD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	
	gcd_1_arg.a = n1;
	gcd_1_arg.b = n2;
	result_1 = gcd_1(&gcd_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("\n gcd(%d,%d) = %d",n1,n2,*result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
root_prog_1(char *host,int rr)
{
	CLIENT *clnt;
	float  *result_1;
	numb  root_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ROOT_PROG, ROOT_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	root_1_arg.a=rr;
	result_1 = root_1(&root_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}else
	{
		printf("\n sqrt(%d) id %f",rr,*result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
swap_prog_1(char *host,int a,int b)
{
	CLIENT *clnt;
	numb  *result_1;
	numb  swap_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SWAP_PROG, SWAP_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	swap_1_arg.a=a;
	swap_1_arg.b=b;
	result_1 = swap_1(&swap_1_arg, clnt);
	if (result_1 == (numb *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("\n swap %d %d",result_1->a,result_1->b);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
state_prog_1(char *host)
{
	CLIENT *clnt;
	stat  *result_1;
	arr  state_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, STATE_PROG, STATE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	printf("\n Enter the size of array : ");
	scanf("%d",&state_1_arg.len);
	printf("\n Enter the elements: ");
	int i=0;
	for(i=0;i<state_1_arg.len;i++)
	{
		scanf("%d",&state_1_arg.ar[i]);
	}
	result_1 = state_1(&state_1_arg, clnt);
	if (result_1 == (stat *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("\n Maximum = %d     Minimum = %d    Average = %d",result_1->max,result_1->min,result_1->avg);

	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
cmp_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	strings  cmp_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CMP_PROG, CMP_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	getchar();
	printf("\n Enter the 1st string : ");
	scanf("%[^\n]s",cmp_1_arg.str1);
	getchar();
	printf("\n Enter the 2nd string : ");
	scanf("%[^\n]s",cmp_1_arg.str2);
	printf("\n %s  %s",cmp_1_arg.str1,cmp_1_arg.str2);
	result_1 = cmp_1(&cmp_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		if(*result_1 == 0)
		{
			printf("\n Both the strings are same.");
		}else
		{
			printf("\n Strings are different.");
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
sub_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	strings  sub_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SUB_PROG, SUB_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	getchar();
	printf("\n Enter the 1st string : ");
	scanf("%[^\n]s",sub_1_arg.str1);
	getchar();
	printf("\n Enter the 2nd string : ");
	scanf("%[^\n]s",sub_1_arg.str2);
	result_1 = sub_1(&sub_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else
	{
		if(*result_1 == -1)
		{
			printf("\n Not a substring");
		}else
		{
			printf("\n Yes it is a subsrting from index %d",*result_1);
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
cont_prog_1(char *host)
{
	CLIENT *clnt;
	strings  *result_1;
	strings  cont_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CONT_PROG, CONT_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	getchar();
	printf("\n Enter the 1st string : ");
	scanf("%[^\n]s",cont_1_arg.str1);
	getchar();
	printf("\n Enter the 2nd string : ");
	scanf("%[^\n]s",cont_1_arg.str2);
	result_1 = cont_1(&cont_1_arg, clnt);
	if (result_1 == (strings *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("\n Conctenated string is : %s",result_1->str1);
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

void
rev_prog_1(char *host)
{
	CLIENT *clnt;
	arr  *result_1;
	arr  rev_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, REV_PROG, REV_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	printf("\n Enter the size of array : ");
	scanf("%d",&rev_1_arg.len);
	printf("\n Enter the elements: ");
	int i=0;
	for(i=0;i<rev_1_arg.len;i++)
	{
		scanf("%d",&rev_1_arg.ar[i]);
	}
	result_1 = rev_1(&rev_1_arg, clnt);
	if (result_1 == (arr *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("\n Array reversed succesfully : ");
		for(i=0;i<result_1	->len;i++)
		{
			printf(" %d",result_1->ar[i]);
		}
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	host = argv[1];
	
	char msg[200];
	int rr;
	int n1,n2;
	int choice,tmp,a,b;
	char c;
	while(1)
	{
		
		printf("\n\n1. String is palindrome or not."
"\n2. Find out given year is Lear Year or not."
"\n3. Find out the GCD of given number."
"\n4. Find out the Square root of given number."
"\n5. Swap two variables without using 3rd variable."
"\n6. Calculate Maximum, Minimum, average of given array."
"\n7. Compare the given two strings."
"\n8. Find out whether given string is substring or not."
"\n9. Concatenate the two strings."
"\n10. Reverse the elements of an array"
"\n11. exit");
		printf("\n\n Enter the number corresponding to task to run that fun : ");
		scanf("%d",&choice);
		switch (choice)
		{
			case 1: printf("Palindrome : ");
				scanf("%s",msg);
				palindrome_prog_1 (host,msg);
				break;

			case 2:printf("\n Leap year : ");
				int year;
				scanf("%d",&year);
				leap_prog_1 (host,year);
				break;

			case 3:
				printf("\n gcd : ");
				scanf("%d%d",&n1,&n2);
				gcd_prog_1 (host,n1,n2);
				break;

			case 4:
				printf("\n Square root of : ");
				scanf("%d",&rr);
				root_prog_1 (host,rr);
				break;

			case 5:printf("\n swap : ");
				int a,b;
				scanf("%d%d",&a,&b);
				swap_prog_1 (host,a,b);
				break;

			case 6:state_prog_1 (host);
				break;

			case 7:cmp_prog_1 (host);
				break;

			case 8:sub_prog_1 (host);
				break;

			case 9:cont_prog_1 (host);
				break;

			case 10:rev_prog_1 (host); 
				break;
				
			case 11: printf("\nexit\n");
				return 0;
				break;

			default: printf("\n Invalid input try again \n");
				break; 
		}
	
	}
/*	printf("Palindrome : ");
	scanf("%s",msg);
	palindrome_prog_1 (host,msg);

	printf("\n Leap year : ");
	int year;
	scanf("%d",&year);
	leap_prog_1 (host,year);

	int n1,n2;
	printf("\n gcd : ");
	scanf("%d%d",&n1,&n2);
	gcd_prog_1 (host,n1,n2);


	int rr;
	printf("\n Square root of : ");
	scanf("%d",&rr);
	root_prog_1 (host,rr);


	printf("\n swap : ");
	int a,b;
	scanf("%d%d",&a,&b);
	swap_prog_1 (host,a,b);

	state_prog_1 (host);

	cmp_prog_1 (host);
	
	sub_prog_1 (host);
	cont_prog_1 (host);

	rev_prog_1 (host);
*/	printf("\n");
exit (0);
}
