/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ASSIGN6_H_RPCGEN
#define _ASSIGN6_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numb {
	int a;
	int b;
};
typedef struct numb numb;

struct strings {
	char str1[200];
	char str2[200];
};
typedef struct strings strings;

struct arr {
	int ar[200];
	int len;
};
typedef struct arr arr;

struct stat {
	int max;
	int min;
	int avg;
};
typedef struct stat stat;

#define PALINDROME_PROG 0x4562871
#define PALINDROME_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define palindrome 1
extern  int * palindrome_1(strings *, CLIENT *);
extern  int * palindrome_1_svc(strings *, struct svc_req *);
extern int palindrome_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define palindrome 1
extern  int * palindrome_1();
extern  int * palindrome_1_svc();
extern int palindrome_prog_1_freeresult ();
#endif /* K&R C */

#define LEAP_PROG 0x4562873
#define LEAP_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define leap 1
extern  int * leap_1(numb *, CLIENT *);
extern  int * leap_1_svc(numb *, struct svc_req *);
extern int leap_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define leap 1
extern  int * leap_1();
extern  int * leap_1_svc();
extern int leap_prog_1_freeresult ();
#endif /* K&R C */

#define GCD_PROG 0x4562875
#define GCD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define gcd 1
extern  int * gcd_1(numb *, CLIENT *);
extern  int * gcd_1_svc(numb *, struct svc_req *);
extern int gcd_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define gcd 1
extern  int * gcd_1();
extern  int * gcd_1_svc();
extern int gcd_prog_1_freeresult ();
#endif /* K&R C */

#define ROOT_PROG 0x4562877
#define ROOT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define root 1
extern  float * root_1(numb *, CLIENT *);
extern  float * root_1_svc(numb *, struct svc_req *);
extern int root_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define root 1
extern  float * root_1();
extern  float * root_1_svc();
extern int root_prog_1_freeresult ();
#endif /* K&R C */

#define SWAP_PROG 0x4562879
#define SWAP_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define swap 1
extern  numb * swap_1(numb *, CLIENT *);
extern  numb * swap_1_svc(numb *, struct svc_req *);
extern int swap_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define swap 1
extern  numb * swap_1();
extern  numb * swap_1_svc();
extern int swap_prog_1_freeresult ();
#endif /* K&R C */

#define STATE_PROG 0x4562881
#define STATE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define state 1
extern  stat * state_1(arr *, CLIENT *);
extern  stat * state_1_svc(arr *, struct svc_req *);
extern int state_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define state 1
extern  stat * state_1();
extern  stat * state_1_svc();
extern int state_prog_1_freeresult ();
#endif /* K&R C */

#define CMP_PROG 0x4562883
#define CMP_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define cmp 1
extern  int * cmp_1(strings *, CLIENT *);
extern  int * cmp_1_svc(strings *, struct svc_req *);
extern int cmp_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define cmp 1
extern  int * cmp_1();
extern  int * cmp_1_svc();
extern int cmp_prog_1_freeresult ();
#endif /* K&R C */

#define SUB_PROG 0x4562885
#define SUB_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define sub 1
extern  int * sub_1(strings *, CLIENT *);
extern  int * sub_1_svc(strings *, struct svc_req *);
extern int sub_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sub 1
extern  int * sub_1();
extern  int * sub_1_svc();
extern int sub_prog_1_freeresult ();
#endif /* K&R C */

#define CONT_PROG 0x4562887
#define CONT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define cont 1
extern  strings * cont_1(strings *, CLIENT *);
extern  strings * cont_1_svc(strings *, struct svc_req *);
extern int cont_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define cont 1
extern  strings * cont_1();
extern  strings * cont_1_svc();
extern int cont_prog_1_freeresult ();
#endif /* K&R C */

#define REV_PROG 0x4562889
#define REV_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define rev 1
extern  arr * rev_1(arr *, CLIENT *);
extern  arr * rev_1_svc(arr *, struct svc_req *);
extern int rev_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define rev 1
extern  arr * rev_1();
extern  arr * rev_1_svc();
extern int rev_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numb (XDR *, numb*);
extern  bool_t xdr_strings (XDR *, strings*);
extern  bool_t xdr_arr (XDR *, arr*);
extern  bool_t xdr_stat (XDR *, stat*);

#else /* K&R C */
extern bool_t xdr_numb ();
extern bool_t xdr_strings ();
extern bool_t xdr_arr ();
extern bool_t xdr_stat ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ASSIGN6_H_RPCGEN */
