/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "assign6.h"

int *
palindrome_1_svc(strings *argp, struct svc_req *rqstp)
{
	static int  result=0;
	int l=0;
	int h= strlen(argp->str1) -1;
//	printf("helo");
	while(h>l)
	{
		if(argp->str1[h] != argp->str1[l])
		{
			result = 1;
		}
		h--;
		l++;
	}

	return &result;
}

int *
leap_1_svc(numb *argp, struct svc_req *rqstp)
{
	static int  result;
	int year = argp->a;
	
	if( ( (year%4 == 0) && ( (year%400 == 0) || (year%100 != 0) ) ) )  
	{  
//        printf("%d is a leap year", &year);  
		result = 1;
	} else {  
//        printf("%d is not a leap year", &year);  
		result = 0;
	}  

	return &result;
}

int *
gcd_1_svc(numb *argp, struct svc_req *rqstp)
{
	static int  result;

	int num1 = argp->a, num2 = argp->b;  
      
    while (num1 != num2)   
    {  
     
        if (num1 > num2)  
        {  
            num1 = num1 - num2;   
        }    
        else  
        {  
            num2 = num2 - num1;  
        }               
    }   
	result = num2;
	return &result;
}

float *
root_1_svc(numb *argp, struct svc_req *rqstp)
{
	static float  result;
	
	int number = argp->a;
	int start = 0, end = argp->a;
    int mid;
 
    
    float ans;
 
    while (start <= end) {
 
        mid = (start + end) / 2;
 
        if (mid * mid == number) {
            ans = mid;
            break;
        }

        if (mid * mid < number) {
            ans=start;
            start = mid + 1;
        }else {
            end = mid - 1;
        }
    }
 
    float increment = 0.1;
    for (int i = 0; i < 5; i++) {
        while (ans * ans <= number) {
            ans += increment;
        }
        ans = ans - increment;
        increment = increment / 10;
    }
    	result = ans;

	return &result;
}

numb *
swap_1_svc(numb *argp, struct svc_req *rqstp)
{
	static numb  result;

	argp->a += argp->b;
	argp->b = argp->a - argp->b;
	argp->a -= argp->b;
	//printf("hello");
	//printf("%d %d",argp->a,argp->b);
	result.a=argp->a;
	result.b=argp->b;
	return &result;
}

stat *
state_1_svc(arr *argp, struct svc_req *rqstp)
{
	static stat  result;
	int min,max,avg=0;
	min = argp->ar[0];
	max = argp->ar[0];
	avg = argp->ar[0];
	int i=1;
	for(i=1;i<argp->len;i++)
	{
		if(max < argp->ar[i])
		{
			max = argp->ar[i];
		}
		if(min > argp->ar[i])
		{
			min = argp->ar[i];
		}

		avg += argp->ar[i];
	}


	result.min = min;
	result.max = max;
	result.avg = avg / argp->len;
	

	return &result;
}

int *
cmp_1_svc(strings *argp, struct svc_req *rqstp)
{
	static int  result;
	result = 0; 
	int l1=strlen(argp->str1);
	int l2=strlen(argp->str2);
	if(l1 != l2)
	{
		
		result = 1;
	}
	else
	{
		int i=0;
		for(i=0;i<l1;i++)
		{
			if(argp->str1[i] != argp->str2[i])
			{
				printf("\n %c %c",argp->str1[i],argp->str2[i]);
				result = 1;
				break;
			}
		}
	}
	
	return &result;
}

int *
sub_1_svc(strings *argp, struct svc_req *rqstp)
{
	static int  result;

	int counter = 0; 
    int i = 0;
	int l1 = strlen(argp->str1);
	int l2 = strlen(argp->str2);

    for(;i<l1;i++)
    {
        if(counter == l2)
            break;
        if(argp->str2[counter] == argp->str1[i])
        {
            counter++;
        }
      else
        {
            if(counter > 0)
            {
                i -= counter;
            }
            counter = 0;
        }
    }
    
	result = (counter < l2)?( -1 ) : (i-counter);
	return &result;
}

strings *
cont_1_svc(strings *argp, struct svc_req *rqstp)
{
	static strings  result;

	int i,l1=strlen(argp->str1);
	for(i=0;i<l1;i++)
	{
		result.str1[i] =argp->str1[i];
	}
	
	for(i=0;i<=strlen(argp->str2);i++)
	{
		result.str1[l1 + i] = argp->str2[i];
	}
	return &result;
}

arr *
rev_1_svc(arr *argp, struct svc_req *rqstp)
{
	static arr  result;

	int i;
	for(i=0;i<argp->len;i++)
	{
		result.ar[i] = argp->ar[argp->len - i -1];
	}
	result.len = argp->len;
	return &result;
}
