/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "assign.h"

int *
fact_1_svc(numb *argp, struct svc_req *rqstp)
{
	static int  result;

	int n=argp->a;
	if(n== 0 || n==1)
	{
		result =1;
		return &result;
	}
	
	int i;
	result=1;
	
	for(i=2;i<=n;i++)
	{
		result *= i;	
	}


	return &result;
}

int *
prime_1_svc(numb *argp, struct svc_req *rqstp)
{
	static int  result;

	int n = argp->a;
	int i=0,flag=1;
	
	for(i=2;i<= n/2;i++)
	{
		if(n%i == 0)
		{
			flag=0;
			break;
		}
	}
	
	result = flag;

	return &result;
}

int *
calcb_1_svc(calc *argp, struct svc_req *rqstp)
{
	static int  result;
	
	int a=argp->a;
	int b=argp->b;
	char c=argp->c;
	
	switch(c)
	{
		case '+':
			result = a + b;
			break;
	
		case '-':
			result = a - b;
			break;

		case '*':
			result = a*b;
			break;

		case '/':
			if(b!=0)
				result = a / b;
			else
				result = -1;
			break;
	
	}
	
	
	return &result;
}

arr *
fib_1_svc(numb *argp, struct svc_req *rqstp)
{
	static arr  result;
	int n = argp->a;
	int i;
 
    	result.ar[0]=0;
    	result.ar[1]=1;
    	
    	for(i=2;i<=n;i++)
    	{
    		result.ar[i] = result.ar[i-1] + result.ar[i-2];
    	}
    	
    	result.len = n+1;
    	return &result;
}

int *
findmax_1_svc(arr *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->ar[0];
	
	int i;
	for(i=1;i<argp->len;i++)
	{
		if(result < argp->ar[i])
		{
			result = argp->ar[i];
		}
	}

	return &result;
}
