/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ASSIGN_H_RPCGEN
#define _ASSIGN_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numb {
	int a;
};
typedef struct numb numb;

struct calc {
	int a;
	int b;
	char c;
};
typedef struct calc calc;

struct arr {
	int ar[200];
	int len;
};
typedef struct arr arr;

#define FACT_PROG 0x4562877
#define FACT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define fact 1
extern  int * fact_1(numb *, CLIENT *);
extern  int * fact_1_svc(numb *, struct svc_req *);
extern int fact_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define fact 1
extern  int * fact_1();
extern  int * fact_1_svc();
extern int fact_prog_1_freeresult ();
#endif /* K&R C */

#define PRIME_PROG 0x4562879
#define PRIME_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define prime 1
extern  int * prime_1(numb *, CLIENT *);
extern  int * prime_1_svc(numb *, struct svc_req *);
extern int prime_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define prime 1
extern  int * prime_1();
extern  int * prime_1_svc();
extern int prime_prog_1_freeresult ();
#endif /* K&R C */

#define CALCB_PROG 0x4562882
#define CALCB_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define calcb 1
extern  int * calcb_1(calc *, CLIENT *);
extern  int * calcb_1_svc(calc *, struct svc_req *);
extern int calcb_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define calcb 1
extern  int * calcb_1();
extern  int * calcb_1_svc();
extern int calcb_prog_1_freeresult ();
#endif /* K&R C */

#define FIB_PROG 0x4562884
#define FIB_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define fib 1
extern  arr * fib_1(numb *, CLIENT *);
extern  arr * fib_1_svc(numb *, struct svc_req *);
extern int fib_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define fib 1
extern  arr * fib_1();
extern  arr * fib_1_svc();
extern int fib_prog_1_freeresult ();
#endif /* K&R C */

#define FINDMAX_PROG 0x4562886
#define FINDMAX_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define findmax 1
extern  int * findmax_1(arr *, CLIENT *);
extern  int * findmax_1_svc(arr *, struct svc_req *);
extern int findmax_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define findmax 1
extern  int * findmax_1();
extern  int * findmax_1_svc();
extern int findmax_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numb (XDR *, numb*);
extern  bool_t xdr_calc (XDR *, calc*);
extern  bool_t xdr_arr (XDR *, arr*);

#else /* K&R C */
extern bool_t xdr_numb ();
extern bool_t xdr_calc ();
extern bool_t xdr_arr ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ASSIGN_H_RPCGEN */
