/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "assign.h"


void
fact_prog_1(char *host,int x)
{
	CLIENT *clnt;
	int  *result_1;
	numb  fact_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, FACT_PROG, FACT_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
		fact_1_arg.a=x;
	result_1 = fact_1(&fact_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("\n factorial of %d is %d",x,*result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
prime_prog_1(char *host,int x)
{
	CLIENT *clnt;
	int  *result_1;
	numb  prime_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PRIME_PROG, PRIME_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	prime_1_arg.a=x;
	result_1 = prime_1(&prime_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else
	{
		if(*result_1 == 1)
		{
			printf("\n%d is PRIME",x);
		}
		else
		{
			printf("\n %d is NOT PRIME",x);
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
calcb_prog_1(char *host,int a,int b,char c)
{
	CLIENT *clnt;
	int  *result_1;
	calc  calcb_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCB_PROG, CALCB_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	calcb_1_arg.a=a;
	calcb_1_arg.b=b;
	calcb_1_arg.c=c;
	result_1 = calcb_1(&calcb_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else
	{
		printf("\n %d %c %d = %d",a,c,b,*result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
fib_prog_1(char *host,int x)
{
	CLIENT *clnt;
	arr  *result_1;
	numb  fib_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, FIB_PROG, FIB_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	fib_1_arg.a=x;
	result_1 = fib_1(&fib_1_arg, clnt);
	if (result_1 == (arr *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		int i=0;
		printf("\n");
		for(i=0;i<result_1->len;i++)
		{
			printf(" %d ",result_1->ar[i]);
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
findmax_prog_1(char *host,int a[],int n)
{
	CLIENT *clnt;
	int  *result_1;
	arr  findmax_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, FINDMAX_PROG, FINDMAX_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	int i=0;
	for(i=0;i<n;i++)
	{
		findmax_1_arg.ar[i]=a[i];
	}
	findmax_1_arg.len=n;
	result_1 = findmax_1(&findmax_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else
	{
		printf("\n Max element in the array is : %d",*result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void fff(char host[])
{
	int n,i;
	printf("\nEnter the size of array : ");
	scanf("%d",&n);
	int a[n];
	printf("\nEnter the elements : ");
	for(i=0;i<n;i++)
	{
		scanf("%d",&a[i]);
	}

	findmax_prog_1 (host,a,n);

}

int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 1) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	
	int choice,tmp,a,b;
	char c;
	while(1)
	{
		
		printf("\n\n1) Find out the factorial of given number.\n2) Implement Calculator (Basic operation).\n3) Find out whether given number is Prime Number or not.\n4) Print out the Fibonacci series till the given number.\n5) Find the maximum value of an array of integers using RPC.\n6) exit");
		printf("\n\n Enter the number corresponding to task to run that fun : ");
		scanf("%d",&choice);
		switch (choice)
		{
			case 1: printf("\n----Factorial------\n");
				printf("\nEnter the number : ");
				scanf("%d",&tmp);
				fact_prog_1 (host,tmp);
				break;

			case 2: printf("\n----Calculator------\n");
				printf("\nEnter data like 2 + 3 : ");
				scanf("%d",&a);
				scanf("%c",&c);scanf("%c",&c);				
				scanf("%d",&b);
				
				calcb_prog_1 (host,a,b,c);
				break;

			case 3: printf("\n----Prime------\n");
				printf("\nEnter the number : ");
				scanf("%d",&tmp);
				prime_prog_1 (host,tmp);
				break;

			case 4: printf("\n----Fibonacci------\n");
				printf("\nEnter the number : ");
				scanf("%d",&tmp);
				fib_prog_1 (host,tmp);
				break;

			case 5: printf("\n----Prime------\n");
				fff(host);
				break;

			case 6: printf("\nexit\n");
				return 0;
				break;

			default: printf("\n Invalid input try again \n");
				break; 
		}
	
	}
//	fact_prog_1 (host);
//	prime_prog_1 (host);
//	calcb_prog_1 (host);
//	fib_prog_1 (host,atoi(argv[2]));
	
/*	int n,i;
	printf("\nEnter the size of array : ");
	scanf("%d",&n);
	int a[n];
	printf("\nEnter the elements : ");
	for(i=0;i<n;i++)
	{
		scanf("%d",&a[i]);
	}
	
	findmax_prog_1 (host,a,n);
*/
	printf("\n");
exit (0);
}
